from flask import Flask, render_template, request
from keras.layers import Input, Lambda, Dense, Flatten
from keras.models import Model
from keras.applications.vgg16 import VGG16
from keras.applications.vgg16 import preprocess_input
from keras.preprocessing import image
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.models import load_model
import pickle
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np

app = Flask(__name__)

model = load_model('G56.H5')  
dic = {0: 'Aloevera', 1: 'Banana', 2: 'Bilimbi', 3: 'Brinjal', 4: 'Cantaloupe', 5: 'Cassava', 6: 'Coconut', 7: 'Corn', 8: 'Cucumber', 9: 'Curcuma', 10: 'Galangal', 11: 'Ginger', 12: 'Guava', 13: 'Kale', 14: 'Longbeans', 15: 'Mango', 16: 'Melon', 17: 'Orange', 18: 'Paddy', 19: 'Papaya', 20: 'Peper chili', 21: 'Pineapple', 22: 'Pomelo', 23: 'Shallot', 24: 'Soybeans', 25: 'Spinach', 26: 'Sweet potato', 27: 'Tobacco', 28: 'Waterapple', 29: 'Watermelon'}

@app.route('/', methods=['GET'])
def hello():
    return render_template('hello.html')

   

@app.route('/output', methods=['GET','POST'])
def output():
    if request.method == 'POST':
        
        img = request.files['imagefile']
        image_path = "static/" + img.filename
        img.save(image_path)
        prediction = predict(image_path)
        if(prediction==dic[0]):
            
                name="Aloe barbadensis Miller"
                descrition="Aloe vera is a herb with succulent grey to green leaves that are arranged in a rosette. The leaves sometimes have white spots on their surfaces and most commonly used as medicine for centuries, to treat sunburn, rashes, and other skin conditions."
                benefit="It may improve skin and prevent wrinkles.Aloe vera may also help treat constipation.It accelerates wound healing.Aloe vera gel contains antibacterial properties and powerful antioxidants."
                seffect="Common side effects of aloevera include: Nausea, Diarrhea, Stomach cramps, Vomiting, Skin irritation when applied topically"
        elif(prediction==dic[1]):
                
                name="Musa"
                descrition="A banana is a fruit which is produced by different varieties of herbaceous flowering plant. This fruit is usually firm and is variable in colour and size. It is curved and elongated. The flesh is usually covered with a brown, purple, yellow or green rind. Bananas generally hang in clusters from the banana tree."
                benefit="Bananas are extremely nutritional as it contains around 1% protein, 23% carbohydrates and 75% water. Bananas are extremely nutritional as it contains around 1% protein, 23% carbohydrates and 75% water. Scientifically proven properties of bananas include: It have the ability to manage diabetes by reducing elevated blood glucose.It have antioxidant properties.It have anti-microbial properties. "
                seffect="A few side effects related to the consumption of bananas includes: consuming bananas can sometimes result in banana allergy due to the presence of banana proteins which trigger an abnormal immune response.Migraine is a common side effect of yellow coloured fruits due to the presence of tyramine which triggers headaches.Due to its high sugar and carbohydrate content, bananas may cause tooth decay or cavities. "
        elif(prediction==dic[2]):
                
                name="Averrhoa bilimbi"
                descrition="Bililmbi fruits are often eaten raw, used to make wine, vinegar and pickles and substitute for tamarind in dishes and also be used as a flavouring agent.Bilimbi or Averrhoa bilimbi, is a folk remedy for many ailments.It is frequently grown in gardens across the plains of India and thrives in all the country’s warmest regions.It is often eaten raw, used to make wine, vinegar and pickles and substitute for tamarind in dishes and also be used as a flavouring agent."
                benefit="Bilimbi may contain bioactive compounds like amino acids, citric acid, cyanidin–3–O–h–D–glucoside, phenolics and sugars.It lowers cholesterol.It may improve heart health.It may improve liver health and also to heal wounds. "
                seffect="It may cause uncontrollable hiccups and sometimes mental confusion. It may cause seizures. High oxalate levels on the consumption of bilimbi may cause the deposition of calcium oxalate crystals. "
        elif(prediction==dic[3]):
                name="Solanum Melongena"
                descrition="The brinjal or eggplant or aubergine, provides fiber and a range of nutrients. This low calorie vegetable features in the Mediterranean diet.It can provide at least 5% of a person’s daily requirement of fiber, copper, manganese, B-6, and thiamine. It also contains other vitamins and minerals."
                benefit="It contains fiber, and this may benefit cholesterol levels.The polyphenols in eggplant may help protect the body from cancer.It contain fiber and are low in calories — they can contribute to a healthful, low-calorie diet.It also contains the antioxidants lutein and zeaxanthin.Lutein appears to play a role in eye health, and it may help prevent age-related macular degeneration, which can lead to vision loss in older people."
                seffect="Consuming excessive amount of it can result in any form can potentially lead to stomach irritation. The cooked form of the plant could also worsen symptoms for people who suffer from irritable bowel syndrome (IBS). People with pre-existing inflammatory intestinal disorders should avoid eating this vegetable as it may cause irritations or discomfort."
        elif(prediction==dic[4]):
                name="Cucumis melo var. cantalupensis"
                descrition="The cantaloupe is a juicy, orange summer fruit that’s related to the watermelon and honeydew melon.Other names for cantaloupe include muskmelon, mush melon, rock melon, and Persian melon. They are a member of the Cucurbitaceae family, along with honeydew melons, watermelons, and cucumbers.This type of fruit also contains a variety of vitamins, minerals, and antioxidants.The water, antioxidants, vitamins, and minerals in cantaloupe can provide a variety of health benefits."
                benefit="It’s low in carbs. Cantaloupes are 90% water. That’s almost as juicy as a watermelon. The high amount of liquid content gives cantaloupes a low glycemic load score of 4. That means your body digests it slowly and it won’t make your blood sugar spike. So it’s a great pick for people with diabetes.It may help fight diseases. Compounds called phytonutrients in cantaloupes give it anti-inflammatory properties. It’s a good part of a healthy diet. "
                seffect="Having too much potassium in your blood increases your risk of a heart attack. Eating too much cantaloupe may also be hard on your intestines and cause diarrhea, stomach cramps, and other digestive problems.Risk Of Missing Out On Other Essential Macronutrients"        
        elif(prediction==dic[5]):
                name="Manihot esculenta"
                descrition="Cassava is a root vegetable. It is the underground part of the cassava shrub, which has the Latin name Manihot esculenta. Like potatoes and yams, it is a tuber crop. Cassava roots have a similar shape to sweet potatoes. People can also eat the leaves of the cassava plant."
                benefit="Cassava is a rich, affordable source of carbohydrates.Cassava is a good source of vitamin C, thiamine, riboflavin, and niacin. The leaves, which are also edible if a person cooks them or dries them in the sun, can contain up to 25% protein.Cassava is a source of resistant starch, which scientists suggest can boost a person’s gut health by helping nurture beneficial gut bacteria."
                seffect="Eating raw or incorrectly prepared cassava can lead to severe side effects: paralyzed legs in children,low levels of iodine, increased risk of goiter and intoxication and eventual death. In addition to containing naturally occurring cyanide, cassava can also absorb pollutants from the area in which it grows, which can be close to roads and factories."
        elif(prediction==dic[6]):
                name="Cocos nucifera"
                descrition="Coconut is the fruit of the coconut palm, which grows in tropical places around the worldCoconut, a fruit of coconut palm can be eaten as food or used as medicine. It contains a hard shell, edible white flesh, and a clear liquid that is commonly used as a beverage and is sometimes referred to as water Coconut flesh, sometimes known as meat is aromatic, chewy, and flavorful.. It can be eaten as food or used as medicine.Coconuts contain a high amount of a saturated fat called medium chain triglycerides. These fats work differently than other types of saturated fat in the body. They might increase fat burning and reduce fat storage. Coconut flour, which is made from coconut, contains high amounts of dietary fiber."
                benefit="Coconut minerals are involved in a variety of bodily functions. Manganese is highly rich in coconuts, and it is necessary for bone health as well as the metabolism of carbohydrates, proteins, and cholesterol.Coconut water can help you avoid a stroke or a heart attack. You've probably heard of coconut water being promoted as a heart-healthy beverage. Because the potassium in coconut water helps to counteract the blood pressure-raising effects of sodium, drinking coconut water may help prevent heart disease.Those who want to lose weight can drink coconut water. Coconut water has few calories and is easy on the stomach.Coconut oil has been linked to some potential skin benefits, such as reducing inflammation, keeping skin moisturized, and aiding in wound healing."
                seffect="Higher doses of coconut water increase blood potassium levels, causing irregular heartbeat and kidney problems. Some peoples are allergic to Coconut milk and its products. Therefore, it has to be taken with precautions. Coconut oil can cause nausea if consumed in excess."
        elif(prediction==dic[7]):
                name="Zea mays"
                descrition="Corn, also known as maize, is a starchy vegetable that comes as kernels on a cob, covered by a husk. Corn is one of the most popular vegetables in the U.S. that sometimes gets a bad rap because it has a lot of natural sugar and carbs. But don't overlook the health benefits of this versatile veggie."
                benefit="The fiber in corn helps you stay full for longer between meals. It also feeds healthy bacteria in your digestive tract, which may help protect against colon cancer.Popcorn may also help prevent diverticulitis, a condition that causes pouches in the walls of your colon. In a large study, men who ate more popcorn had a lower risk of getting diverticular disease.Corn is rich in vitamin C, an antioxidant that helps protect your cells from damage and wards off diseases like cancer and heart disease. Yellow corn is a good source of the carotenoids lutein and zeaxanthin, which are good for eye health and help prevent the lens damage that leads to cataracts. Corn also has smaller amounts of vitamins B, E, and K, along with minerals like magnesium and potassium."
                seffect="Corn is a starchy vegetable, like potatoes and peas. That means it has sugar and carbohydrates that can raise your blood sugar levels. It can still be a healthy part of your diet if you don't overdo it. If you have diabetes, you don't necessarily need to avoid corn, but watch your portion sizes.Often, corn gets contaminated by fungi that put off toxins called mycotoxins. If you eat a lot of corn with these toxins, you’re at a higher risk for certain cancers, liver problems, lung issues, and slowing of your immune system." 
        elif(prediction==dic[8]):
                name="Cucumis sativus"
                descrition="Cucumbers have a mild, refreshing taste and a high water content. They can help relieve dehydration and are pleasant to eat in hot weather. People eat cucumber as a savory food, but it is a fruit. It also features in some beauty products.The cucumber is a member of the Cucurbitaceae family. Other members of the family include squash and different kinds of melon, including bitter melon. Cucumbers provide various nutrients but are low in calories, fat, cholesterol, and sodium."
                benefit="Cucumbers consist mostly of water, and they also contain important electrolytes. They can help prevent dehydration in hot weather or after a workout.Cucumber also contains 19.9 milligrams (mg) of calcium. Adults need 1,000–1,200 mg of calcium a day, depending on sex and age. Vitamin K helps improve calcium absorption. Together, these nutrients can contribute to good bone health. As a member of the Cucurbitaceae family of plants, cucumbers contain high levels of bitter-tasting nutrients known as cucurbitacin. According to an article in the International Journal of Health Services, cucurbitacins may help prevent cancer by stopping cancer cells from reproducing.Fiber can help manage cholesterol and prevent related cardiovascular problems."
                seffect="Cucumber is safe for most people to eat, but there are some points to consider such as : Blood clotting, some people find some types of cucumber hard to digest, allergy.Some cucurbitacins are toxic for people to consume. Eating bottle gourd, for example, has caused illness in some people."        
        elif(prediction==dic[9]):
                name="Curcuma(Turmeric)"
                descrition="Turmeric is a flowering plant, Curcuma longa, of the ginger family, Zingiberaceae, the rhizomes of which are used in cooking. The plant is a perennial, rhizomatous, herbaceous plant native to the Indian subcontinent and Southeast Asia that requires temperatures between 20 and 30 °C and high annual rainfall to thrive"
                benefit="Curcuma is the primary bioactive substance in turmeric. It has anti-inflammatory properties, and there is decent evidence that it can alleviate various conditions, from chronic pain to depression. Curcumin has poor bioavailability on its own, and thus it is often combined with Black Pepper or with lipids. Curcumin is the primary bioactive substance in turmeric. It has anti-inflammatory properties, and there is decent evidence that it can alleviate various conditions, from chronic pain to depression. Curcumin has poor bioavailability on its own, and thus it is often combined with Black Pepper or with lipids."
                seffect="Turmeric may worsen acid reflux.It may cause stomach upset and indigestion.Increase the risk of kidney stones.Lower blood sugar levels.May cause liver damage in high amounts.May interfere with medications that slow blood clotting.High blood pressure.Increased risk of bleeding."
        elif(prediction==dic[10]):
                name="Alpinia galanga"
                descrition="It is widely cultivated in many countries such as China, Indonesia, India, and Sri Lanka. It grows well in hot temperatures and abundant sunlight. However, it grows equally well in bushes, jungles, and open areas. It grows up to 3.5 cm tall and has underground roots. Depending on the species, these underground roots, also known as rhizomes, may be reddish-brown, whitish-yellow, orange, or pink. These rhizomes grow 2.5 to 10 cm long with an upright stem-like structure covered with leaves. "
                benefit="Galangal has various properties, such as: It may act as anti-microbial.It may act as an antioxidant (acts against free radicals).It may show anti-inflammatory property.It may help enhance immunity.It may help protect the liver.It may show anti-allergic properties (helps to fight allergic reactions).It may show anti-cancer properties.It may act as an antiplatelet agent (helps to prevent blood clots).It may help enhance digestion "
                seffect="As far as the side effects of galangal are concerned, no significant study has been documented.1 However, if you experience any adverse reactions to consuming it, immediately contact your Ayurvedic physician who has prescribed it. They will be able to treat you appropriately. You are advised to avoid using galangal as medicine without consulting with your Ayurvedic physician. "
        elif(prediction==dic[11]):
                name="Zingiber officinale"
                descrition="Ginger is a flowering tropical plant that grows in China, India, Africa, the Caribbean, and other warm climates. The root of the ginger plant is well-known as a spice and flavoring. It's been a traditional remedy in many cultures for thousands of years.Ginger is a common folk treatment for upset stomach and nausea."
                benefit="Ginger seems to aid digestion and saliva flow. Studies found that taking ginger could ease nausea and vomiting in some pregnant women.But pregnant women should be careful with ginger. Some experts worry that it could raise the risk of miscarriage, especially in high doses.Ginger seems to help with nausea caused by vertigo as well. There's mixed evidence about whether it helps with nausea caused by motion sickness, surgery, or chemotherapy.Ginger does seem to help with painful periods. In one study, more than 60% of women felt that ginger lessened pain.There's strong evidence that ginger may ease osteoarthritis pain."
                seffect="In small doses, ginger has few side effects. High doses of ginger -- more than 5 grams a day -- increase the chances of side effects. Ginger on the skin may cause a rash.Eating or drinking it may cause:gas,heartburn,Upset stomach,mouth irritation.Ginger may raise the risk of bleeding. If you have a bleeding disorder, it may not be safe. Always tell your doctor about herbal medicines you take, including ginger."
        elif(prediction==dic[12]):
                name="Psidium guajava"
                descrition="Guava, (Psidium guajava), small tropical tree or shrub of the family Myrtaceae, cultivated for its edible fruits. Guava trees are native to tropical America and are grown in tropical and subtropical areas worldwide. Guava fruits are processed into jams, jellies, and preserves and are common pastry fillings.The guava tree is an evergreen tree that can grow up to a height of 3 to 10 metres. "
                benefit="Guava fruits are amazingly rich in antioxidants, vitamin C, potassium, and fiber. This remarkable nutrient content gives them many health benefits.Guavas may help boost heart health in a number of ways and  guava leaf extract may reduce the pain intensity of menstrual cramps.Guavas are an excellent source of dietary fiber.Guavas are a weight-loss-friendly food."
                seffect="If we eat too much guava, it will make us gassy. The main cause comes from the amount of gas produced by bacteria that eat the sugar fructose. 2.2. Causes diarrhea or irritable bowel syndrome Due to fructose malabsorption, you may experience diarrhea or other digestive problems. "
        elif(prediction==dic[13]):
                name="Brassica oleracea var. sabellica"
                descrition="Kale is low in carbohydrates and is also rich in fibres, both of which may promote weight loss. It may promote bowel movements due to the presence of fibre. Being a good source of calcium and Vitamin K, kale may help in boosting bone health. Consumption of kale may help in detoxifying the body."
                benefit="It may help in managing malnutrition problems. Being a good source of iron and Vitamin C, it may help in boosting immunity. Antioxidants like lutein present in kale may lead to healthier skin.The presence of Vitamin K and iron may improve blood clotting.Being a good source of omega-3 fatty acids and beta-carotene, it may improve hair growth.Consumption of kale may help in managing macular degeneration because of the presence of lutein and zeaxanthin. "
                seffect="Consumption of kale in excess can lead to constipation and stomach irritation. Due to the presence of oxalates, kale can increase the risk of kidney stones. Kale contains goitrogens, substances that inhibit the synthesis of thyroid hormone. So, its intake can increase the risk of iodine deficiency. Being rich in iron, consumption of kale in excess can lead to iron toxicity. Due to its potent antioxidant profile, it can trigger an allergic reaction in allergy-prone individuals. However, if you experience any adverse reactions to kale, it is advised to discontinue its intake and immediately contact a doctor or your Ayurvedic physician who has prescribed it"        
                  
        elif(prediction==dic[14]):
                name="Vigna unguiculata ssp. sesquipedalis"
                descrition="Long beans, also known as snake beans or Chinese long beans, are a type of legume that belong to the Vigna genus. They are long and slender, with a green exterior and a tender interior, and are commonly used in Asian cuisine. Long beans can be eaten cooked or raw and are a good source of nutrition."
                benefit="Nutritious: Long beans are low in calories but high in fiber, vitamin C, vitamin A, and potassium.Digestive health: The fiber content in long beans can promote digestive health and prevent constipation.Cardiovascular health: The potassium content in long beans can help regulate blood pressure and improve cardiovascular health.Anti-inflammatory: Long beans contain compounds with anti-inflammatory properties, which can help reduce inflammation and related conditions."
                seffect="Allergies: Some people may be allergic to long beans, which can cause symptoms such as itching, swelling, and difficulty breathing.Gastrointestinal problems: Eating too many long beans can cause gastrointestinal problems, including bloating, gas, and diarrhea.Interaction with medication: Long beans may interact with certain medications, such as blood thinners, and should be consumed in moderation or avoided altogether in these cases."
        elif(prediction==dic[15]):
                name="Mangifera indica"
                descrition="Mango is a tropical fruit that belongs to the genus Mangifera. It is a juicy and sweet fruit with a fibrous texture, and is available in a variety of sizes, shapes, and colors. Mangoes are a popular ingredient in many cuisines, and can be eaten ripe or unripe, cooked or raw."
                benefit="Nutritious: Mangoes are a good source of vitamins A and C, as well as potassium and fiber.Boosts immunity: The high vitamin C content in mangoes can help boost the immune system, protecting against infections and illnesses.Anti-inflammatory: Mangoes contain compounds with anti-inflammatory properties, which can help reduce inflammation and related conditions.Improves digestion: The fiber content in mangoes can aid digestion and prevent constipation.Promotes eye health: The vitamin A content in mangoes can help promote eye health and prevent vision loss."
                seffect="Allergies: Some people may be allergic to mangoes, which can cause symptoms such as itching, swelling, and difficulty breathing.High in sugar: Mangoes are high in natural sugar and should be consumed in moderation by people with diabetes or those trying to manage their blood sugar levels.Interactions with medication: Mangoes may interact with certain medications, such as blood thinners, and should be consumed in moderation or avoided altogether in these cases."
        elif(prediction==dic[16]):
                name="Cucumis melo"
                descrition="Melon is a sweet and juicy fruit that belongs to the Cucurbitaceae family. Here are some of the benefits and side effects of consuming melon:"
                benefit="Good for hydration: Melon is rich in water content, making it an excellent fruit for keeping the body hydrated.High in nutrients: Melon is packed with essential vitamins and minerals like Vitamin C, Vitamin A, potassium, and magnesium.Helps in weight loss: Melon is low in calories and high in fiber, making it an excellent fruit for weight loss.Boosts immunity: The high Vitamin C content in melon helps boost the immune system, reducing the risk of infections.Good for digestion: Melon is rich in fiber, which helps promote healthy digestion.Regulates blood pressure: The high potassium content in melon helps regulate blood pressure levels."
                seffect="May cause allergic reactions: Some people may be allergic to melons, leading to symptoms like rashes, hives, and itching.May cause digestive problems: Consuming too much melon can cause digestive issues like bloating, gas, and diarrhea.May interact with medication: Melon may interact with certain medications like blood thinners, leading to adverse effects.May cause electrolyte imbalance: Consuming too much melon can cause an imbalance in electrolytes like potassium, leading to muscle weakness and cramps."
        elif(prediction==dic[17]):
                name="Citrus x sinensis"
                descrition="Oranges are a popular citrus fruit that is rich in vitamins, minerals, and antioxidants. Here are some of the benefits and side effects of consuming oranges:"
                benefit="Rich in Vitamin C: Oranges are an excellent source of Vitamin C, which helps boost the immune system and fights off infections.Promotes healthy skin: The antioxidants in oranges help protect the skin from damage caused by free radicals, promoting healthy skin.Good for digestion: Oranges are rich in fiber, which helps promote healthy digestion and prevent constipation.Helps in weight loss: Oranges are low in calories and high in fiber, making them an excellent fruit for weight loss.Regulates blood pressure: Oranges are rich in potassium, which helps regulate blood pressure levels."
                seffect="May cause allergic reactions: Some people may be allergic to oranges, leading to symptoms like rashes, hives, and itching.May cause heartburn: Oranges are acidic, and consuming too much of them can lead to heartburn and acid reflux.May cause dental problems: The high sugar content in oranges can lead to dental problems like cavities and tooth decay.May interact with medication: Oranges may interact with certain medications like statins, leading to adverse effects.May cause stomach problems: Consuming too many oranges can lead to stomach"
        elif(prediction==dic[18]):
                name="Oryza sativa"
                descrition="Paddy or rice is a cereal grain that is cultivated worldwide for its edible seeds. It is a staple food for many people in Asia and parts of Africa and Latin America. Paddy is usually harvested and processed to remove the husk, bran, and germ, leaving behind the white rice that is commonly consumed."
                benefit="Provides energy: Paddy is a rich source of carbohydrates, which provides the body with energy.Contains essential nutrients: Paddy is a good source of essential vitamins and minerals, such as thiamine, niacin, and iron.Promotes digestion: Paddy is high in dietary fiber, which helps to promote digestion and prevent constipation.Helps control blood sugar: Paddy has a low glycemic index, which means it can help control blood sugar levels.May reduce the risk of chronic diseases: Paddy contains antioxidants, which may help reduce the risk of chronic diseases such as heart disease, cancer, and diabetes."
                seffect="May contain arsenic: Some paddy may contain high levels of arsenic, which can be harmful to health.May contribute to weight gain: Paddy is high in carbohydrates, which can contribute to weight gain if consumed in excess.May cause digestive issues: Some people may experience digestive issues such as bloating, gas, and diarrhea after consuming paddy. May cause allergic reactions: Some people may be allergic to paddy, which can cause symptoms such as itching, hives, and difficulty breathing.May contribute to high blood pressure: Paddy is high in sodium, which can contribute to high blood pressure if consumed in excess."
        elif(prediction==dic[19]):
                name="Carica papaya"
                descrition="Papaya is a tropical fruit that is native to Central and South America but is now grown in many parts of the world. It is pear-shaped and has a soft, orange flesh and black seeds in the center. Papaya is commonly consumed as a fresh fruit or used in salads, smoothies, and other dishes."
                benefit="Rich in nutrients: Papaya is a good source of vitamins and minerals, including vitamin C, vitamin A, potassium, and folate.May aid digestion: Papaya contains an enzyme called papain, which can help improve digestion and reduce inflammation in the digestive tract.May promote skin health: Papaya contains antioxidants and vitamin C, which can help promote skin health and reduce the signs of aging.May reduce the risk of chronic diseases: Papaya contains antioxidants and other compounds that may help reduce the risk of chronic diseases such as heart disease, cancer, and diabetes.May boost immunity: Papaya is high in vitamin C, which can help boost the immune system and reduce the risk of infections"
                seffect="May cause allergic reactions: Some people may be allergic to papaya, which can cause symptoms such as itching, hives, and difficulty breathing.May interact with medications: Papaya contains compounds that can interact with certain medications, so people taking medication should talk to their doctor before consuming papaya.May cause digestive issues: Some people may experience digestive issues such as bloating, gas, and diarrhea after consuming papaya.May increase the risk of bleeding: Papaya contains compounds that can increase the risk of bleeding, so people with bleeding disorders or taking blood-thinning medications should avoid consuming large amounts of papaya."
        elif(prediction==dic[20]):
                name="Capsicum"
                descrition="Pepper chili, also known as chili pepper or hot pepper, is a type of fruit from the genus Capsicum. It is widely used in cooking and is known for its spicy taste. Here are some of the benefits and side effects of pepper chili"
                benefit="Anti-inflammatory properties: The capsaicin in chili peppers has anti-inflammatory properties that may help reduce inflammation in the body.Pain relief: Capsaicin also has pain-relieving properties, and is often used in creams and patches for pain relief.Boosts metabolism: Chili peppers contain a compound called capsaicin which may help boost metabolism and aid in weight loss.Rich in nutrients: Chili peppers are rich in vitamins A and C, and also contain potassium, iron, and fiber.May improve heart health: The capsaicin in chili peppers may help improve heart health by reducing inflammation and improving blood flow."
                seffect="Digestive issues: Eating too much chili pepper can cause digestive issues like diarrhea, bloating, and gas.Heartburn: The capsaicin in chili peppers can cause heartburn in some people.Skin irritation: Handling chili peppers can cause skin irritation and burning sensations.Allergies: Some people may be allergic to chili peppers, which can cause allergic reactions like hives, difficulty breathing, and swelling."
        elif(prediction==dic[21]):
                name="Ananas comosus"
                descrition="Pineapple is a tropical fruit that grows on the plant Ananas comosus. It has a rough, spiky exterior and a juicy, yellow interior with a sweet, tangy taste. Pineapples are rich in vitamins, minerals, and enzymes, making them a nutritious addition to your diet."
                benefit="Rich in Vitamin C: Pineapples are an excellent source of vitamin C, which supports a healthy immune system and helps to protect against infections and diseases.Digestive Health: Pineapples contain bromelain, a digestive enzyme that helps to break down proteins in the body. This can help to improve digestion and alleviate digestive issues such as bloating, gas, and constipation.Anti-inflammatory: Bromelain in pineapple also has anti-inflammatory properties, which can help to reduce inflammation and swelling in the body.Heart Health: Pineapples are rich in potassium, which can help to lower blood pressure and reduce the risk of heart disease."
                seffect="Allergic Reactions: Some people may be allergic to pineapple, and can experience symptoms such as itching, swelling, and difficulty breathing.Mouth Irritation: Pineapple contains enzymes that can cause mouth irritation, especially if you eat a lot of it. This can cause soreness, redness, and sensitivity.Upset Stomach: Eating too much pineapple can also lead to digestive issues such as diarrhea, nausea, and vomiting.Skin Irritation: Pineapple juice can cause skin irritation or rash when exposed to sunlight. This is called phytophotodermatitis and occurs due to a combination of sunlight and chemicals in the pineapple juice."
        elif(prediction==dic[22]):
                name="Citrus Maxima or Citrus Grandis"
                descrition="Pomelo is a citrus fruit that is native to Southeast Asia. It is the largest fruit in the citrus family and has a thick, pale yellow or green rind, with a sweet and slightly sour flesh inside. Pomelo is an excellent source of vitamins, minerals, and antioxidants, making it a nutritious addition to your diet."
                benefit="Immune Boosting: Pomelo is high in vitamin C, which is essential for a healthy immune system and helps to protect against infections and diseases.Digestive Health: Pomelo is rich in fiber, which can help to improve digestion and alleviate digestive issues such as constipation, bloating, and gas.Heart Health: Pomelo contains potassium, which can help to regulate blood pressure and reduce the risk of heart disease.Skin Health: Pomelo is rich in antioxidants, which can help to protect the skin against damage from free radicals and prevent signs of aging."
                seffect="Allergic Reactions: Some people may be allergic to pomelo, and can experience symptoms such as itching, swelling, and difficulty breathing.Medication Interactions: Pomelo can interact with certain medications, such as statins used to lower cholesterol, and increase the risk of side effects.Grapefruit Juice Effect: Pomelo is closely related to grapefruit, and can also affect the metabolism of certain medications. So, it is advisable to consult with a doctor before consuming pomelo if you are on any medication."       
        elif(prediction==dic[23]):
                name="Allium cepa gr. aggregatum"
                descrition="Shallots are a type of onion that have a milder and sweeter taste. They have a brown papery skin and are smaller than regular onions. Shallots are used in many different cuisines around the world to add flavor and aroma to dishes."
                benefit="Immune Boosting: Shallots are a good source of vitamin C, which supports a healthy immune system and helps to protect against infections and diseases.Heart Health: Shallots contain compounds called flavonoids and sulfur compounds that can help to reduce the risk of heart disease by lowering blood pressure, reducing inflammation, and improving cholesterol levels.Antioxidant Properties: Shallots are rich in antioxidants, which can help to protect the body against damage from free radicals and prevent the development of chronic diseases.Digestive Health: Shallots contain a type of fiber called fructooligosaccharides (FOS) that can promote the growth of beneficial bacteria in the gut, improving digestion and reducing the risk of digestive issues such as constipation."
                seffect="Allergic Reactions: Some people may be allergic to shallots, and can experience symptoms such as itching, swelling, and difficulty breathing.Digestive Issues: Eating too many shallots can cause digestive issues such as bloating, gas, and diarrhea, particularly in people who are sensitive to FOS.Blood Thinning: Shallots contain compounds that can thin the blood, so people taking blood-thinning medication should be cautious when consuming shallots."
        elif(prediction==dic[24]):
                name=" Glycine max"
                descrition="Soybeans are a type of legume that are commonly used in many different cuisines around the world. They are small, oval-shaped beans that can be eaten in a variety of forms, including as tofu, tempeh, soy milk, and edamame."
                benefit="Heart Health: Soybeans contain compounds called isoflavones that can help to lower cholesterol levels and reduce the risk of heart disease.Bone Health: Soybeans are a good source of calcium, magnesium, and other minerals that are important for maintaining strong and healthy bones.Digestive Health: Soybeans contain fiber, which can help to improve digestion and prevent digestive issues such as constipation and diarrhea.Cancer Prevention: Soybeans contain compounds that have been shown to have anti-cancer properties, particularly against breast and prostate cancers."
                seffect="Allergic Reactions: Some people may be allergic to soybeans, and can experience symptoms such as itching, swelling, and difficulty breathing.Hormonal Effects: Soybeans contain compounds that can mimic the effects of estrogen in the body, so people with certain hormone-sensitive conditions such as breast cancer should be cautious when consuming soybeans.Digestive Issues: Eating too many soybeans can cause digestive issues such as bloating, gas, and diarrhea, particularly in people who are sensitive to fiber."       
        
        elif(prediction==dic[25]):
                name="Spinacia oleracea"
                descrition="Spinach is a leafy green vegetable that is widely used in many different cuisines around the world. It has a distinctive taste and can be eaten raw or cooked in a variety of dishes."
                benefit="Nutrient-Rich: Spinach is rich in vitamins and minerals, including vitamins A, C, and K, iron, calcium, and magnesium.Heart Health: Spinach contains compounds called nitrates that can help to improve blood flow and lower blood pressure, reducing the risk of heart disease.Anti-Inflammatory Properties: Spinach contains antioxidants and other compounds that can help to reduce inflammation in the body, preventing chronic diseases such as cancer and arthritis.Eye Health: Spinach is rich in lutein and zeaxanthin, two antioxidants that are important for maintaining healthy eyesight and reducing the risk of age-related eye diseases."
                seffect="Oxalate Content: Spinach contains oxalates, which can contribute to the formation of kidney stones in some people.Interactions with Medications: Spinach can interact with certain medications, particularly blood-thinning medications, so it is important to consult with a doctor before consuming spinach if you are on any medication.Allergic Reactions: Some people may be allergic to spinach, and can experience symptoms such as itching, swelling, and difficulty breathing.High Vitamin K Content: Spinach is high in vitamin K, which can interfere with blood-thinning medications and may be a concern for people with certain medical conditions."
        elif(prediction==dic[26]):
                name="Ipomoea batatas"
                descrition="Sweet potato is a starchy root vegetable that is commonly used in many different cuisines around the world. It has a sweet and nutty flavor and can be cooked in a variety of ways, including baking, roasting, and boiling."
                benefit="Nutrient-Rich: Sweet potatoes are rich in vitamins and minerals, including vitamins A, C, and B6, potassium, and fiber.Blood Sugar Regulation: Sweet potatoes have a low glycemic index, which means they can help to regulate blood sugar levels and prevent spikes and crashes.Digestive Health: Sweet potatoes are rich in fiber, which can help to improve digestion and prevent digestive issues such as constipation.Eye Health: Sweet potatoes are rich in beta-carotene, an antioxidant that is important for maintaining healthy eyesight and reducing the risk of age-related eye diseases.Anti-Inflammatory Properties: Sweet potatoes contain compounds that can help to reduce inflammation in the body, preventing chronic diseases such as cancer and arthritis."
                seffect="Allergic Reactions: Some people may be allergic to sweet potatoes, and can experience symptoms such as itching, swelling, and difficulty breathing.High Potassium Content: Sweet potatoes are high in potassium, which can be a concern for people with kidney disease or who are taking medications that affect potassium levels.High Vitamin A Content: Sweet potatoes are high in vitamin A, and consuming too much vitamin A can be toxic and cause a range of symptoms such as nausea, dizziness, and even liver damage.Carbohydrate Content: Sweet potatoes are a starchy vegetable and are higher in carbohydrates than some other vegetables, so people on low-carbohydrate diets should consume them in moderation."        
        elif(prediction==dic[27]):
                name="Nicotiana"
                descrition="Tobacco is a plant that belongs to the Nicotiana genus, and is grown mainly for its leaves, which are used to make tobacco products such as cigarettes, cigars, and chewing tobacco. The leaves of the tobacco plant contain the addictive drug nicotine, which is responsible for the stimulating and addictive effects of tobacco use."
                benefit="There are no known health benefits of tobacco use."
                seffect="Addiction: Tobacco use is highly addictive due to the presence of nicotine, which can lead to physical dependence and withdrawal symptoms when use is stopped.Increased risk of cancer: Tobacco use is a leading cause of cancer, including lung cancer, throat cancer, and mouth cancer.Cardiovascular disease: Tobacco use is a major risk factor for heart disease and stroke, due to its negative impact on the cardiovascular system.Respiratory problems: Tobacco use can cause a range of respiratory problems, including chronic bronchitis, emphysema, and asthmaReproductive health: Tobacco use can negatively impact reproductive health, leading to reduced fertility and increased risk of pregnancy complications.Secondhand smoke: Exposure to secondhand smoke from tobacco products can cause a range of health problems, including respiratory problems and an increased risk of cancer"
        elif(prediction==dic[28]):
                name="Syzygium samarangense"
                descrition="Water apple is a tasty tropical fruit from South East Asia, which is renowned for its ability to quench thirst. Its ripe fruit is bright red in colour and has a crisp texture. This sweet fruit is also rich in fibre, calcium, magnesium, potassium and vitamin C. Water Apple is also referred to as Rose Apple, Java Apple, Chambakka or Jambaka fruit, Wax Apple and Watery Rose Apple. Their effectiveness in quenching thirst comes from the abundant water content in them. Making pickles, jellies or syrup from unripe green fruits is common. Unripe green water apples can be used in dishes as well as eaten raw with a sprinkle of salt. "
                benefit="Dietary fibres in this fruit aid in preventing bloating and constipation. The water apple’s seeds also control digestive issues that result in vomiting and diarrhoea.Canreduce the risk of developing prostate and breast cancer. Keeps you hydrated. Sunstroke may also be treated successfully with it. Early medical research proves that consuming water apples can reduce the risk of developing prostate and breast cancer.  One can apply water and apple juice all over the face and wash it off after it dries. This can balance oil production and act as a moisturising mask."
                seffect="The leaves, seeds, and roots of rose apples contain a high amount of cyanide or prussic acid that is dangerous for health. Over-consumption of the fruit apart from its skin and flesh is not advisable. Always consult a doctor before including the water apple in your diet."
        elif(prediction==dic[29]):
                name="Citrullus lanatus"
                descrition="Watermelon is a fruit that grows on a vine-like flowering plant native to West Africa. It is typically round or oblong in shape and has a green rind with a juicy red or pink interior flesh that contains numerous small black seeds. Watermelon is known for its refreshing and sweet taste, and is often eaten raw, juiced, or used in salads, smoothies, and desserts."
                benefit="Hydrating: Watermelon is over 90% water, making it an excellent hydrating fruit.Nutritious: Watermelon is low in calories but high in nutrients, including vitamin C, vitamin A, potassium, and lycopene.Heart health: Lycopene in watermelon has been linked to improved heart health and reduced risk of heart disease.Anti-inflammatory: Watermelon contains compounds that have anti-inflammatory properties, which may help reduce inflammation and related diseases."
                seffect="Allergies: Some people may be allergic to watermelon, which can cause symptoms such as itching, swelling, and difficulty breathing.Diarrhea: Consuming large amounts of watermelon can cause diarrhea due to its high water and fiber content.Blood sugar: Watermelon is a relatively high-glycemic fruit, meaning it can cause a rapid spike in blood sugar levels in people with diabetes or insulin resistance.Interaction with medication: Watermelon can interact with certain medications, such as blood thinners, and should be consumed in moderation or avoided altogether in these cases."
        
        
        else:
            name="No Data Found"
            descrition=""
            benefit=""
            seffect=""
            
        return render_template("second.html", prediction_text='{}'.format(prediction),name="{}".format(name),descrition="{}".format(descrition),benefit="{}".format(benefit),image_path=image_path,seffect="{}".format(seffect))

def predict(image_path):
    img = load_img(image_path, target_size=(120, 120, 3))
    img = img_to_array(img)
    img = img / 255
    img = np.expand_dims(img, [0])
    answer = model.predict(img)
    y_class = answer.argmax(axis=-1)
    y = " ".join(str(x) for x in y_class)
    y = int(y)
    prediction = dic[y]
    return prediction
        
if __name__ == '__main__':
    app.run(port=3000, debug=True)
